export const buses = [
  {
    id: 1,
    name: "Express Shuttle",
    img: "assets/images/BusImage.jpg",
    departureCity: "City A",
    arrivalCity: "City B",
    departureTime: "08:00 AM",
    ticketPrice: 25.99,
  },
  {
    id: 2,
    name: "City Hopper",
    img: "assets/images/BusImage.jpg",
    departureCity: "City B",
    arrivalCity: "City C",
    departureTime: "10:30 AM",
    ticketPrice: 19.99,
  },
  {
    id: 3,
    name: "Metro Voyager",
    img: "assets/images/BusImage.jpg",
    departureCity: "City C",
    arrivalCity: "City D",
    departureTime: "01:15 PM",
    ticketPrice: 22.5,
  },
  {
    id: 4,
    name: "Coastal Explorer",
    img: "assets/images/BusImage.jpg",
    departureCity: "City D",
    arrivalCity: "City E",
    departureTime: "03:45 PM",
    ticketPrice: 30.75,
  },
  {
    id: 5,
    name: "Rapid Transit",
    img: "assets/images/BusImage.jpg",
    departureCity: "City E",
    arrivalCity: "City F",
    departureTime: "06:20 PM",
    ticketPrice: 27.5,
  },
];
