export const plans = [
  {
    id: 1,
    name: "Coastal Retreat",
    image: "assets/images/CoastalRetreat.jpg",
    days: "5 days",
    price: "$1,200",
    locations: "Coastal towns",
    plan: "Relax by the beach, explore local cuisine",
    route: "Starting from City A to City B",
    date: "July 15 - July 19, 2023",
    pick_up_point: "City A Airport",
    drop_point: "City B Beach Resort",
  },
  {
    id: 2,
    name: "Mountain Adventure",
    image: "assets/images/MountainAdventure.jpg",
    days: "7 days",
    price: "$2,500",
    locations: "Mountainous region",
    plan: "Hiking, camping, wildlife spotting",
    route: "Starting from City C to City D",
    date: "September 5 - September 11, 2023",
    pick_up_point: "City C Hotel",
    drop_point: "City D Mountain Lodge",
  },
  {
    id: 3,
    name: "Historical Tour",
    image: "assets/images/HistoricalTour.jpg",
    days: "3 days",
    price: "$800",
    locations: "Historical landmarks",
    plan: "Guided tours, museum visits",
    route: "Starting from City E to City F",
    date: "November 10 - November 12, 2023",
    pick_up_point: "City E Train Station",
    drop_point: "City F Hotel",
  },
  {
    id: 4,
    name: "Desert Safari",
    image: "assets/images/DesertSafari.jpg",
    days: "4 days",
    price: "$1,500",
    locations: "Desert oasis",
    plan: "Dune bashing, camel rides",
    route: "Starting from City G to City H",
    date: "April 20 - April 23, 2023",
    pick_up_point: "City G Airport",
    drop_point: "City H Desert Camp",
  },
  {
    id: 5,
    name: "Cultural Expedition",
    image: "assets/images/CulturalExpedition.jpg",
    days: "6 days",
    price: "$1,800",
    locations: "Cultural heritage sites",
    plan: "Visiting temples, local festivals",
    route: "Starting from City I to City J",
    date: "February 8 - February 13, 2023",
    pick_up_point: "City I Hotel",
    drop_point: "City J Heritage Center",
  },
];
